services:

  sparkling-redis:
    container_name: sparkling-redis
    hostname: sparkling-redis
    image: redis:7.2-bookworm
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning # --requirepass <password>
    volumes: 
      - redis-volume:/data
    networks:
      - sparkling-bridge

  event-engine:
    container_name: event-engine
    image: jonathanarns/sparkling-event-engine
    build: 
      context: ./
      dockerfile: ./event-engine.Dockerfile
    depends_on:
      - sparkling-redis
    networks:
      - sparkling-bridge
    environment:
      - RUST_BACKTRACE=1
    env_file:
      - .env
    restart: on-failure

  web:
    container_name: server
    image: jonathanarns/sparkling-server
    build: 
      context: ./
      dockerfile: ./server.Dockerfile
    depends_on:
      - sparkling-redis
    ports:
      - "80:8080"
    networks:
      - sparkling-bridge
    environment:
      - RUST_BACKTRACE=1
    restart: on-failure

  # feature-uploader:
  #   container_name: feature-uploader
  #   image: fabianzeiher/sparkling-feature-uploader
  #   build: ./feature-uploader
  #   depends_on:
  #     - event-engine
  #     - sparkling-redis
  #   env_file:
  #     - .env
  #   networks:
  #     - sparkling-bridge

  # inference-pipeline:
  #   container_name: inference-pipeline
  #   image: fabianzeiher/sparkling-inference-pipeline
  #   build: ./inference-pipeline
  #   depends_on:
  #     - event-engine
  #     - sparkling-redis
  #   env_file:
  #     - .env
  #   networks:
  #     - sparkling-bridge
  
  # rt-data-exporter:
  #   container_name: rt-data-exporter
  #   image: fabianzeiher/sparkling-rt-data-exporter
  #   build: ./rt-data-exporter
  #   depends_on:
  #     - event-engine
  #     - sparkling-redis
  #   environment:
  #     - RUST_BACKTRACE=1
  #     - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  #   networks:
  #     - sparkling-bridge
  #   volumes:
  #     - $HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro

volumes:
  redis-volume:
    driver: local

networks:
  sparkling-bridge:
    driver: bridge
