FROM docker.io/bitnami/spark:3.5

# add python dependencies
RUN pip install pandas pyarrow
# add java dependencies
COPY ./spark-sql-kafka-0-10_2.12-3.5.0.jar /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar

COPY . .
