apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-data-exporter
  labels:
    app: rt-data-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rt-data-exporter
  template:
    metadata:
      labels:
        app: rt-data-exporter
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: fabi-account-creds
      containers:
      - name: rt-data-exporter
        image: docker.io/fabianzeiher/sparkling-rt-data-exporter
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: api-key-secret
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: RUST_BACKTRACE
            value: "1"
        resources: 
          requests:
            cpu: 100m
            memory: 100M
          limits: 
            cpu: 200m
            memory: 500M
