
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-data-exporter
  labels:
    app: rt-data-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rt-data-exporter
  template:
    metadata:
      labels:
        app: rt-data-exporter
    spec:
      containers:
      - name: rt-data-exporter
        image: docker.io/jonathanarns/sparkling-rt-data-exporter
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: api-key-secret 
        resources: 
          requests:
            cpu: 100m
            memory: 100M
          limits: 
            cpu: 200m
            memory: 500M
