
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-client
  labels:
    app: spark-client
spec:
  template:
    spec:
      containers:
      - name: spark-client
        image: docker.io/fabianzeiher/sparkling-spark
        # do not use command, it would break HDFS authentication
        args: ["spark-submit", "--master", "spark://spark:7077", "./metadata_join.py"]
        envFrom:
          - secretRef:
              name: api-key-secret
      restartPolicy: OnFailure