apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sparkling
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 1G
        cpu: 500m
      limits:
        memory: 2G
        cpu: 1000m
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 0.5G
        cpu: 250m
      limits:
        memory: 0.5G
        cpu: 250m
  entityOperator:
    topicOperator: 
      resources:
        requests:
          memory: 0.5G
          cpu: 250m
        limits:
          memory: 0.5G
          cpu: 500m
    userOperator: 
      resources:
        requests:
          memory: 0.5G
          cpu: 250m
        limits:
          memory: 0.5G
          cpu: 500m
