

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: docker.io/jonathanarns/sparkling-app
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources: 
          requests:
            cpu: 150m
            memory: 150M
          limits: 
            cpu: 300m
            memory: 250M
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    name: web-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: web-app
  type: LoadBalancer
  loadBalancerIP: "34.88.70.203"
